# Use root/example as user/password credentials
version: '3.8'

services:
  server:
    build: .
    restart: unless-stopped
    command: /bin/sh -c "/app/go-challenege migrate up --config /app/deployment/env/env.docker.yaml && /app/go-challenege serv --config /app/deployment/env/env.docker.yaml"
    volumes:
      - ./deployment/:/app/deployment/
      - ./messages/:/app/messages/
      - ./dbmigration/:/app/dbmigration/
      - ./docs/:/app/docs/
    networks:
      - app_network
    ports:
      - "8887:8888"
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: vmo
    ports:
      - "27017:27017"
    networks:
      - app_network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - app_network
    depends_on:
      - mongo


networks:
  app_network:
    driver: bridge
