definitions:
  common.AppError:
    properties:
      error_key:
        type: string
      log:
        type: string
      message:
        type: string
      status_code:
        type: integer
      ve:
        items:
          $ref: '#/definitions/common.ValidationErrorField'
        type: array
    type: object
  common.ValidationErrorField:
    properties:
      errorMessage:
        type: string
      field:
        type: string
      tag:
        type: string
    type: object
  dto.CreateApplicationRequest:
    properties:
      description:
        type: string
      name:
        type: string
    type: object
  dto.UpdateApplicationRequest:
    properties:
      description:
        type: string
      enabled:
        type: boolean
      name:
        type: string
      type:
        type: string
    type: object
info:
  contact:
    email: thuocnv@vmodev.com
    name: Cesc Nguyen
  description: This is Auth Service API.
  title: Auth Service API
  version: "1.0"
paths:
  /api/v1/applications:
    post:
      consumes:
      - application/json
      description: Create Application
      parameters:
      - description: Create Application
        in: body
        name: Permission
        required: true
        schema:
          $ref: '#/definitions/dto.CreateApplicationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.AppError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/common.AppError'
      security:
      - ApiKeyAuth: []
      summary: Create Application
      tags:
      - Applications
  /api/v1/applications/{id}:
    delete:
      consumes:
      - application/json
      description: Delete Application
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.AppError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/common.AppError'
      security:
      - ApiKeyAuth: []
      summary: Delete Application
      tags:
      - Applications
    get:
      consumes:
      - application/json
      description: Detail Application
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.AppError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/common.AppError'
      security:
      - ApiKeyAuth: []
      summary: Detail Application
      tags:
      - Applications
    put:
      consumes:
      - application/json
      description: Update Application
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      - description: Update Application
        in: body
        name: role
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateApplicationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.AppError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/common.AppError'
      security:
      - ApiKeyAuth: []
      summary: Update Application
      tags:
      - Applications
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
